# Generated by Django 4.1 on 2023-01-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100, null=True)),
                ("score", models.IntegerField()),
                ("clearTime", models.IntegerField()),
                ("regiDate", models.DateField(max_length=100)),
            ],
        ),
    ]
