# Generated by Django 4.1 on 2023-01-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ballmungApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Emp",
            new_name="rankInfo",
        ),
    ]
