# Generated by Django 4.1 on 2023-01-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzleApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
